version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nome_do_seu_banco
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      #POSTGRES_ENCODING: UTF-8  # Configuração de codificação UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
